// <auto-generated />
using System;
using GestionLegalP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionLegalP.Migrations
{
    [DbContext(typeof(GestionLegalPContext))]
    partial class GestionLegalPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionLegalP.Dominio.CasoDocumento", b =>
                {
                    b.Property<int>("Id_CasoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_CasoDocumento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAdjunta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_CasoLegal")
                        .HasColumnType("integer");

                    b.Property<int>("Id_DocumentoLegal")
                        .HasColumnType("integer");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_CasoDocumento");

                    b.HasIndex("Id_CasoLegal");

                    b.HasIndex("Id_DocumentoLegal");

                    b.ToTable("CasoDocumento");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.CasoInvolucrado", b =>
                {
                    b.Property<int>("Id_CasoInvolucrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_CasoInvolucrado"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescripcionParticipacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_CasoLegal")
                        .HasColumnType("integer");

                    b.Property<string>("RolInvolucrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_CasoInvolucrado");

                    b.HasIndex("Id_CasoLegal");

                    b.ToTable("CasoInvolucrado");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.CasoLegal", b =>
                {
                    b.Property<int>("Id_CasoLegal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_CasoLegal"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoCaso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoCaso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_CasoLegal");

                    b.ToTable("CasoLegal");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.Consentimiento", b =>
                {
                    b.Property<int>("Id_Consentimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Consentimiento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Firmado")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreFirmante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentescoFirmante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoTratamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Consentimiento");

                    b.ToTable("Consentimiento");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.ConsentimientoDocumento", b =>
                {
                    b.Property<int>("Id_ConsentimientoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_ConsentimientoDocumento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsociacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Consentimiento")
                        .HasColumnType("integer");

                    b.Property<int>("Id_DocumentoLegal")
                        .HasColumnType("integer");

                    b.HasKey("Id_ConsentimientoDocumento");

                    b.HasIndex("Id_Consentimiento");

                    b.HasIndex("Id_DocumentoLegal");

                    b.ToTable("ConsentimientoDocumento");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.DocumentoDecision", b =>
                {
                    b.Property<int>("Id_DocumentoDecision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_DocumentoDecision"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaDecision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_DocumentoLegal")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDecision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_DocumentoDecision");

                    b.HasIndex("Id_DocumentoLegal");

                    b.ToTable("DocumentoDecision");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.DocumentoLegal", b =>
                {
                    b.Property<int>("Id_DocumentoLegal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_DocumentoLegal"));

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_DocumentoLegal");

                    b.ToTable("DocumentoLegal");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.Regla", b =>
                {
                    b.Property<int>("Id_Regla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Regla"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoRegla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Regla");

                    b.ToTable("Regla");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.Solicitud", b =>
                {
                    b.Property<int>("Id_Solicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Solicitud"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Solicitud");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.SolicitudRevision", b =>
                {
                    b.Property<int>("Id_SolicitudRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_SolicitudRevision"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRevision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Solicitud")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_SolicitudRevision");

                    b.HasIndex("Id_Solicitud");

                    b.ToTable("SolicitudRevision");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.CasoDocumento", b =>
                {
                    b.HasOne("GestionLegalP.Dominio.CasoLegal", "CasoLegal")
                        .WithMany("CasoDocumentos")
                        .HasForeignKey("Id_CasoLegal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionLegalP.Dominio.DocumentoLegal", "DocumentoLegal")
                        .WithMany("CasoDocumentos")
                        .HasForeignKey("Id_DocumentoLegal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CasoLegal");

                    b.Navigation("DocumentoLegal");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.CasoInvolucrado", b =>
                {
                    b.HasOne("GestionLegalP.Dominio.CasoLegal", "CasoLegal")
                        .WithMany("CasoInvolucrados")
                        .HasForeignKey("Id_CasoLegal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CasoLegal");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.ConsentimientoDocumento", b =>
                {
                    b.HasOne("GestionLegalP.Dominio.Consentimiento", "Consentimiento")
                        .WithMany("ConsentimientoDocumentos")
                        .HasForeignKey("Id_Consentimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionLegalP.Dominio.DocumentoLegal", "DocumentoLegal")
                        .WithMany("ConsentimientoDocumentos")
                        .HasForeignKey("Id_DocumentoLegal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consentimiento");

                    b.Navigation("DocumentoLegal");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.DocumentoDecision", b =>
                {
                    b.HasOne("GestionLegalP.Dominio.DocumentoLegal", "DocumentoLegal")
                        .WithMany("DocumentoDecisiones")
                        .HasForeignKey("Id_DocumentoLegal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoLegal");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.SolicitudRevision", b =>
                {
                    b.HasOne("GestionLegalP.Dominio.Solicitud", "Solicitud")
                        .WithMany("SolicitudRevisiones")
                        .HasForeignKey("Id_Solicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.CasoLegal", b =>
                {
                    b.Navigation("CasoDocumentos");

                    b.Navigation("CasoInvolucrados");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.Consentimiento", b =>
                {
                    b.Navigation("ConsentimientoDocumentos");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.DocumentoLegal", b =>
                {
                    b.Navigation("CasoDocumentos");

                    b.Navigation("ConsentimientoDocumentos");

                    b.Navigation("DocumentoDecisiones");
                });

            modelBuilder.Entity("GestionLegalP.Dominio.Solicitud", b =>
                {
                    b.Navigation("SolicitudRevisiones");
                });
#pragma warning restore 612, 618
        }
    }
}
